########################################################################################################################
#Title: Updated booster uptake assignment
#Author: Hailey Park
#Date: January 16th, 2025
########################################################################################################################

#Vaccination Assignment under updated booster coverages (realistic)
#Assign who is getting vaccinated using age-specific and risk-specific coverage rates. Second updated booster coverage in higher risk 
#groups (65+ years, high risk + immunocompromised) also accounted for with the `vax_2` variable

realistic_vax_assignment <- function(df){
  
  #Assign who is getting vaccinated using age-specific and risk-specific coverage rates
  # NOTE: `vax` and `vax_2` assigns who will get 1st and 2nd boosters based on coverage rates.
  #       `vaccine_wave` and `second_vaccine_wave` assigns when those boosters are administered based on historic uptake
  vax_assignment <- df %>% mutate(vax = 0, vax_2 = 0, vax_val = 0, vaccine_wave = 0, second_vaccine_wave = 0, vaccine_wave_val = 0)
  
  #For 0-17 years age bin, assume that 96.7% of 0-17 years are older than 6 months (CRUDE ASSUMPTION)
  age_0_17_index <- which(vax_assignment$age_group == "0-17 years")
  age_0_17_index <- sample(age_0_17_index, length(age_0_17_index) * 0.967)
  
  age_18_29_index <- which(vax_assignment$age_group == "18-29 years")
  age_30_49_index <- which(vax_assignment$age_group == "30-49 years")
  age_50_64_index <- which(vax_assignment$age_group == "50-64 years")
  age_65_74_index <- which(vax_assignment$age_group == "65-74 years")
  age_75_plus_index <- which(vax_assignment$age_group == "75+ years")
  
  risk_healthy_index <- which(vax_assignment$risk_group == "healthy")
  risk_highrisk_index <- which(vax_assignment$risk_group == "higher risk")
  risk_immuno_index <- which(vax_assignment$risk_group == "immunocompromised")
  
  vaccinated <- which(vax_assignment$prior_vacc != "unvax")
  
  #Assign who will receive first updated booster (calibration period)
  vax_assignment$vax[Reduce(intersect, list(age_0_17_index,risk_healthy_index,vaccinated))] <- rbinom(length(Reduce(intersect, list(age_0_17_index,risk_healthy_index,vaccinated))), 1, 0.13 * length(Reduce(intersect, list(age_0_17_index,risk_healthy_index)))/length(Reduce(intersect, list(age_0_17_index,risk_healthy_index,vaccinated))))
  vax_assignment$vax[Reduce(intersect, list(age_0_17_index,risk_highrisk_index,vaccinated))] <- rbinom(length(Reduce(intersect, list(age_0_17_index,risk_highrisk_index,vaccinated))), 1, 0.235 * length(Reduce(intersect, list(age_0_17_index,risk_highrisk_index)))/length(Reduce(intersect, list(age_0_17_index,risk_highrisk_index,vaccinated))))
  vax_assignment$vax[Reduce(intersect, list(age_0_17_index,risk_immuno_index,vaccinated))] <- rbinom(length(Reduce(intersect, list(age_0_17_index,risk_immuno_index,vaccinated))), 1, 0.235 * length(Reduce(intersect, list(age_0_17_index,risk_immuno_index)))/length(Reduce(intersect, list(age_0_17_index,risk_immuno_index,vaccinated))))
  
  vax_assignment$vax[Reduce(intersect, list(age_18_29_index,risk_healthy_index,vaccinated))] <- rbinom(length(Reduce(intersect, list(age_18_29_index,risk_healthy_index,vaccinated))), 1, 0.0926 * length(Reduce(intersect, list(age_18_29_index,risk_healthy_index)))/length(Reduce(intersect, list(age_18_29_index,risk_healthy_index,vaccinated))))
  vax_assignment$vax[Reduce(intersect, list(age_18_29_index,risk_highrisk_index,vaccinated))] <- rbinom(length(Reduce(intersect, list(age_18_29_index,risk_highrisk_index,vaccinated))), 1, 0.1668 * length(Reduce(intersect, list(age_18_29_index,risk_highrisk_index)))/length(Reduce(intersect, list(age_18_29_index,risk_highrisk_index,vaccinated))))
  vax_assignment$vax[Reduce(intersect, list(age_18_29_index,risk_immuno_index,vaccinated))] <- rbinom(length(Reduce(intersect, list(age_18_29_index,risk_immuno_index,vaccinated))), 1, 0.1668 * length(Reduce(intersect, list(age_18_29_index,risk_immuno_index)))/length(Reduce(intersect, list(age_18_29_index,risk_immuno_index,vaccinated))))
  
  vax_assignment$vax[Reduce(intersect, list(age_30_49_index,risk_healthy_index,vaccinated))] <- rbinom(length(Reduce(intersect, list(age_30_49_index,risk_healthy_index,vaccinated))), 1, 0.1308 * length(Reduce(intersect, list(age_30_49_index,risk_healthy_index)))/length(Reduce(intersect, list(age_30_49_index,risk_healthy_index,vaccinated))))
  vax_assignment$vax[Reduce(intersect, list(age_30_49_index,risk_highrisk_index,vaccinated))] <- rbinom(length(Reduce(intersect, list(age_30_49_index,risk_highrisk_index,vaccinated))), 1, 0.2355 * length(Reduce(intersect, list(age_30_49_index,risk_highrisk_index)))/length(Reduce(intersect, list(age_30_49_index,risk_highrisk_index,vaccinated))))
  vax_assignment$vax[Reduce(intersect, list(age_30_49_index,risk_immuno_index,vaccinated))] <- rbinom(length(Reduce(intersect, list(age_30_49_index,risk_immuno_index,vaccinated))), 1, 0.2355 * length(Reduce(intersect, list(age_30_49_index,risk_immuno_index)))/length(Reduce(intersect, list(age_30_49_index,risk_immuno_index,vaccinated))))
  
  vax_assignment$vax[Reduce(intersect, list(age_50_64_index,risk_healthy_index,vaccinated))] <- rbinom(length(Reduce(intersect, list(age_50_64_index,risk_healthy_index,vaccinated))), 1, 0.1439 * length(Reduce(intersect, list(age_50_64_index,risk_healthy_index)))/length(Reduce(intersect, list(age_50_64_index,risk_healthy_index,vaccinated))))
  vax_assignment$vax[Reduce(intersect, list(age_50_64_index,risk_highrisk_index,vaccinated))] <- rbinom(length(Reduce(intersect, list(age_50_64_index,risk_highrisk_index,vaccinated))), 1, 0.2591 * length(Reduce(intersect, list(age_50_64_index,risk_highrisk_index)))/length(Reduce(intersect, list(age_50_64_index,risk_highrisk_index,vaccinated))))
  vax_assignment$vax[Reduce(intersect, list(age_50_64_index,risk_immuno_index,vaccinated))] <- rbinom(length(Reduce(intersect, list(age_50_64_index,risk_immuno_index,vaccinated))), 1, 0.2591 * length(Reduce(intersect, list(age_50_64_index,risk_immuno_index)))/length(Reduce(intersect, list(age_50_64_index,risk_immuno_index,vaccinated))))
  
  vax_assignment$vax[Reduce(intersect, list(age_65_74_index,risk_healthy_index,vaccinated))] <- rbinom(length(Reduce(intersect, list(age_65_74_index,risk_healthy_index,vaccinated))), 1, 0.2228 * length(Reduce(intersect, list(age_65_74_index,risk_healthy_index)))/length(Reduce(intersect, list(age_65_74_index,risk_healthy_index,vaccinated))))
  vax_assignment$vax[Reduce(intersect, list(age_65_74_index,risk_highrisk_index,vaccinated))] <- rbinom(length(Reduce(intersect, list(age_65_74_index,risk_highrisk_index,vaccinated))), 1, 0.4010 * length(Reduce(intersect, list(age_65_74_index,risk_highrisk_index)))/length(Reduce(intersect, list(age_65_74_index,risk_highrisk_index,vaccinated))))
  vax_assignment$vax[Reduce(intersect, list(age_65_74_index,risk_immuno_index,vaccinated))] <- rbinom(length(Reduce(intersect, list(age_65_74_index,risk_immuno_index,vaccinated))), 1, 0.4010 * length(Reduce(intersect, list(age_65_74_index,risk_immuno_index)))/length(Reduce(intersect, list(age_65_74_index,risk_immuno_index,vaccinated))))
  
  vax_assignment$vax[Reduce(intersect, list(age_75_plus_index,risk_healthy_index,vaccinated))] <- rbinom(length(Reduce(intersect, list(age_75_plus_index,risk_healthy_index,vaccinated))), 1, 0.221 * length(Reduce(intersect, list(age_75_plus_index,risk_healthy_index)))/length(Reduce(intersect, list(age_75_plus_index,risk_healthy_index,vaccinated))))
  vax_assignment$vax[Reduce(intersect, list(age_75_plus_index,risk_highrisk_index,vaccinated))] <- rbinom(length(Reduce(intersect, list(age_75_plus_index,risk_highrisk_index,vaccinated))), 1, 0.3979 * length(Reduce(intersect, list(age_75_plus_index,risk_highrisk_index)))/length(Reduce(intersect, list(age_75_plus_index,risk_highrisk_index,vaccinated))))
  vax_assignment$vax[Reduce(intersect, list(age_75_plus_index,risk_immuno_index,vaccinated))] <- rbinom(length(Reduce(intersect, list(age_75_plus_index,risk_immuno_index,vaccinated))), 1, 0.3979 * length(Reduce(intersect, list(age_75_plus_index,risk_immuno_index)))/length(Reduce(intersect, list(age_75_plus_index,risk_immuno_index,vaccinated))))
  
  print(paste0("Percentage of 0-17 years receiving vaccinated: ", length(which(vax_assignment$age_group == "0-17 years" & vax_assignment$vax == 1))/(length(which(vax_assignment$age_group == "0-17 years"))* 0.967)))
  print(paste0("Percentage of 18-29 years receiving vaccinated: ", length(which(vax_assignment$age_group == "18-29 years" & vax_assignment$vax == 1))/length(which(vax_assignment$age_group == "18-29 years"))))
  print(paste0("Percentage of 30-49 years receiving vaccinated: ", length(which(vax_assignment$age_group == "30-49 years" & vax_assignment$vax == 1))/length(which(vax_assignment$age_group == "30-49 years"))))
  print(paste0("Percentage of 50-64 years receiving vaccinated: ",  length(which(vax_assignment$age_group == "50-64 years" & vax_assignment$vax == 1))/length(which(vax_assignment$age_group == "50-64 years"))))
  print(paste0("Percentage of 65-74 years receiving vaccinated: ",  length(which(vax_assignment$age_group == "65-74 years" & vax_assignment$vax == 1))/length(which(vax_assignment$age_group == "65-74 years"))))
  print(paste0("Percentage of 75+ years receiving vaccinated: ",  length(which(vax_assignment$age_group == "75+ years" & vax_assignment$vax == 1))/length(which(vax_assignment$age_group == "75+ years"))))
  print("0.15, 0.113, 0.1596, 0.217, 0.3794, 0.3764")
  
  print(paste0("0-17 years, healthy: % vaccinated: ", length(which(vax_assignment$age_group == "0-17 years" & vax_assignment$risk_group == "healthy" & vax_assignment$vax == 1))/(length(which(vax_assignment$age_group == "0-17 years" & vax_assignment$risk_group == "healthy"))* 0.967)))
  print(paste0("18-29 years, healthy: % vaccinated: ", length(which(vax_assignment$age_group == "18-29 years" & vax_assignment$risk_group == "healthy" & vax_assignment$vax == 1))/length(which(vax_assignment$age_group == "18-29 years" & vax_assignment$risk_group == "healthy"))))
  print(paste0("30-49 years, healthy: % vaccinated: ", length(which(vax_assignment$age_group == "30-49 years" & vax_assignment$risk_group == "healthy" & vax_assignment$vax == 1))/length(which(vax_assignment$age_group == "30-49 years" & vax_assignment$risk_group == "healthy"))))
  print(paste0("50-64 years, healthy: % vaccinated: ",  length(which(vax_assignment$age_group == "50-64 years" & vax_assignment$risk_group == "healthy" & vax_assignment$vax == 1))/length(which(vax_assignment$age_group == "50-64 years" & vax_assignment$risk_group == "healthy"))))
  print(paste0("65-74 years, healthy: % vaccinated: ",  length(which(vax_assignment$age_group == "65-74 years" & vax_assignment$risk_group == "healthy" & vax_assignment$vax == 1))/length(which(vax_assignment$age_group == "65-74 years" & vax_assignment$risk_group == "healthy"))))
  print(paste0("75+ years, healthy: % vaccinated: ",  length(which(vax_assignment$age_group == "75+ years" & vax_assignment$risk_group == "healthy" & vax_assignment$vax == 1))/length(which(vax_assignment$age_group == "75+ years" & vax_assignment$risk_group == "healthy"))))
  
  print(paste0("0-17 years, higher risk: % vaccinated: ", length(which(vax_assignment$age_group == "0-17 years" & vax_assignment$risk_group == "higher risk" & vax_assignment$vax == 1))/(length(which(vax_assignment$age_group == "0-17 years" & vax_assignment$risk_group == "higher risk"))* 0.967)))
  print(paste0("18-29 years, higher risk: % vaccinated: ", length(which(vax_assignment$age_group == "18-29 years" & vax_assignment$risk_group == "higher risk" & vax_assignment$vax == 1))/length(which(vax_assignment$age_group == "18-29 years" & vax_assignment$risk_group == "higher risk"))))
  print(paste0("30-49 years, higher risk: % vaccinated: ", length(which(vax_assignment$age_group == "30-49 years" & vax_assignment$risk_group == "higher risk" & vax_assignment$vax == 1))/length(which(vax_assignment$age_group == "30-49 years" & vax_assignment$risk_group == "higher risk"))))
  print(paste0("50-64 years, higher risk: % vaccinated: ",  length(which(vax_assignment$age_group == "50-64 years" & vax_assignment$risk_group == "higher risk" & vax_assignment$vax == 1))/length(which(vax_assignment$age_group == "50-64 years" & vax_assignment$risk_group == "higher risk"))))
  print(paste0("65-74 years, higher risk: % vaccinated: ",  length(which(vax_assignment$age_group == "65-74 years" & vax_assignment$risk_group == "higher risk" & vax_assignment$vax == 1))/length(which(vax_assignment$age_group == "65-74 years" & vax_assignment$risk_group == "higher risk"))))
  print(paste0("75+ years, higher risk: % vaccinated: ",  length(which(vax_assignment$age_group == "75+ years" & vax_assignment$risk_group == "higher risk" & vax_assignment$vax == 1))/length(which(vax_assignment$age_group == "75+ years" & vax_assignment$risk_group == "higher risk"))))
  
  print(paste0("0-17 years, immunocompromised: % vaccinated: ", length(which(vax_assignment$age_group == "0-17 years" & vax_assignment$risk_group == "immunocompromised" & vax_assignment$vax == 1))/(length(which(vax_assignment$age_group == "0-17 years" & vax_assignment$risk_group == "immunocompromised"))* 0.967)))
  print(paste0("18-29 years, immunocompromised: % vaccinated: ", length(which(vax_assignment$age_group == "18-29 years" & vax_assignment$risk_group == "immunocompromised" & vax_assignment$vax == 1))/length(which(vax_assignment$age_group == "18-29 years" & vax_assignment$risk_group == "immunocompromised"))))
  print(paste0("30-49 years, immunocompromised: % vaccinated: ", length(which(vax_assignment$age_group == "30-49 years" & vax_assignment$risk_group == "immunocompromised" & vax_assignment$vax == 1))/length(which(vax_assignment$age_group == "30-49 years" & vax_assignment$risk_group == "immunocompromised"))))
  print(paste0("50-64 years, immunocompromised: % vaccinated: ",  length(which(vax_assignment$age_group == "50-64 years" & vax_assignment$risk_group == "immunocompromised" & vax_assignment$vax == 1))/length(which(vax_assignment$age_group == "50-64 years" & vax_assignment$risk_group == "immunocompromised"))))
  print(paste0("65-74 years, immunocompromised: % vaccinated: ",  length(which(vax_assignment$age_group == "65-74 years" & vax_assignment$risk_group == "immunocompromised" & vax_assignment$vax == 1))/length(which(vax_assignment$age_group == "65-74 years" & vax_assignment$risk_group == "immunocompromised"))))
  print(paste0("75+ years, immunocompromised: % vaccinated: ",  length(which(vax_assignment$age_group == "75+ years" & vax_assignment$risk_group == "immunocompromised" & vax_assignment$vax == 1))/length(which(vax_assignment$age_group == "75+ years" & vax_assignment$risk_group == "immunocompromised"))))
  
  #Assign who is getting the second dose of the updated booster (filter among individuals who have already been assigned with receiving 1 updated booster) 
  second_dose <- which(vax_assignment$vax == 1)
  
  vax_assignment$vax_2[Reduce(intersect, list(age_18_29_index,risk_immuno_index,second_dose))] <- rbinom(length(Reduce(intersect, list(age_18_29_index,risk_immuno_index,second_dose))), 1, 0.054 * length(Reduce(intersect, list(age_18_29_index,risk_immuno_index)))/length(Reduce(intersect, list(age_18_29_index,risk_immuno_index,second_dose))))
  
  vax_assignment$vax_2[Reduce(intersect, list(age_30_49_index,risk_immuno_index,second_dose))] <- rbinom(length(Reduce(intersect, list(age_30_49_index,risk_immuno_index,second_dose))), 1, 0.054 * length(Reduce(intersect, list(age_30_49_index,risk_immuno_index)))/length(Reduce(intersect, list(age_30_49_index,risk_immuno_index,second_dose))))
  
  vax_assignment$vax_2[Reduce(intersect, list(age_50_64_index,risk_immuno_index,second_dose))] <- rbinom(length(Reduce(intersect, list(age_50_64_index,risk_immuno_index,second_dose))), 1, 0.054 * length(Reduce(intersect, list(age_50_64_index,risk_immuno_index)))/length(Reduce(intersect, list(age_50_64_index,risk_immuno_index,second_dose))))
  
  vax_assignment$vax_2[Reduce(intersect, list(age_65_74_index, second_dose))] <- rbinom(length(Reduce(intersect, list(age_65_74_index, second_dose))), 1, 0.089 * length(Reduce(intersect, list(age_65_74_index)))/length(Reduce(intersect, list(age_65_74_index,second_dose))))
  vax_assignment$vax_2[Reduce(intersect, list(age_75_plus_index,second_dose))] <- rbinom(length(Reduce(intersect, list(age_75_plus_index, second_dose))), 1, 0.089 * length(Reduce(intersect, list(age_75_plus_index)))/length(Reduce(intersect, list(age_75_plus_index,second_dose))))
  
  print(paste0("Percentage of higher risk and immunocompromised receiving second dose: ",  length(which(vax_assignment$risk_group %in% c("higher risk", "immunocompromised") & vax_assignment$vax_2 == 1))/length(which(vax_assignment$risk_group %in% c("higher risk", "immunocompromised")))))
  print(paste0("Percentage of 65-74 years receiving second dose: ",  length(which(vax_assignment$age_group == "65-74 years" & vax_assignment$vax_2 == 1))/length(which(vax_assignment$age_group == "65-74 years"))))
  print(paste0("Percentage of 75+ years receiving second dose: ",  length(which(vax_assignment$age_group == "75+ years" & vax_assignment$vax_2 == 1))/length(which(vax_assignment$age_group == "75+ years"))))
  
  #Assign who will receive the updated booster (validation period)
  val_dose <- which(vax_assignment$vax_2 == 1)
  
  vax_assignment$vax_val[Reduce(intersect, list(age_0_17_index,risk_healthy_index,second_dose))] <- rbinom(length(Reduce(intersect, list(age_0_17_index,risk_healthy_index,second_dose))), 1, 0.1194 * length(Reduce(intersect, list(age_0_17_index,risk_healthy_index)))/length(Reduce(intersect, list(age_0_17_index,risk_healthy_index,second_dose))))
  vax_assignment$vax_val[Reduce(intersect, list(age_0_17_index,risk_highrisk_index,second_dose))] <- 1
  vax_assignment$vax_val[sample(setdiff(Reduce(intersect, list(age_0_17_index,risk_highrisk_index)), second_dose), round(length(Reduce(intersect, list(age_0_17_index,risk_highrisk_index))) * (0.2397 - 0.235)))] <- 1
  vax_assignment$vax_val[Reduce(intersect, list(age_0_17_index,risk_immuno_index,second_dose))] <- 1
  vax_assignment$vax_val[sample(setdiff(Reduce(intersect, list(age_0_17_index,risk_immuno_index)), second_dose), round(length(Reduce(intersect, list(age_0_17_index,risk_immuno_index))) * (0.2397 - 0.235)))] <- 1
  
  vax_assignment$vax_val[Reduce(intersect, list(age_18_29_index,risk_healthy_index,second_dose))] <- rbinom(length(Reduce(intersect, list(age_18_29_index,risk_healthy_index,second_dose))), 1, 0.0758 * length(Reduce(intersect, list(age_18_29_index,risk_healthy_index)))/length(Reduce(intersect, list(age_18_29_index,risk_healthy_index,second_dose))))
  vax_assignment$vax_val[Reduce(intersect, list(age_18_29_index,risk_highrisk_index,val_dose))] <- 1
  vax_assignment$vax_val[sample(setdiff(Reduce(intersect, list(age_18_29_index,risk_highrisk_index, second_dose)), val_dose), round(length(Reduce(intersect, list(age_18_29_index,risk_highrisk_index)))  * (0.1521 + 0.05 - 0.054)))] <- 1
  vax_assignment$vax_val[Reduce(intersect, list(age_18_29_index,risk_immuno_index,val_dose))] <- 1
  vax_assignment$vax_val[sample(setdiff(Reduce(intersect, list(age_18_29_index,risk_immuno_index, second_dose)), val_dose), round(length(Reduce(intersect, list(age_18_29_index,risk_immuno_index))) * (0.1521 - 0.054)))] <- 1
  
  vax_assignment$vax_val[Reduce(intersect, list(age_30_49_index,risk_healthy_index,second_dose))] <- rbinom(length(Reduce(intersect, list(age_30_49_index,risk_healthy_index,second_dose))), 1, 0.121 * length(Reduce(intersect, list(age_30_49_index,risk_healthy_index)))/length(Reduce(intersect, list(age_30_49_index,risk_healthy_index,second_dose))))
  vax_assignment$vax_val[Reduce(intersect, list(age_30_49_index,risk_highrisk_index,second_dose))] <- 1
  vax_assignment$vax_val[sample(setdiff(Reduce(intersect, list(age_30_49_index,risk_highrisk_index)), second_dose), round(length(Reduce(intersect, list(age_30_49_index,risk_highrisk_index))) * (0.2428 - 0.2355)))] <- 1
  vax_assignment$vax_val[Reduce(intersect, list(age_30_49_index,risk_immuno_index,second_dose))] <- 1
  vax_assignment$vax_val[sample(setdiff(Reduce(intersect, list(age_30_49_index,risk_immuno_index)), second_dose), round(length(Reduce(intersect, list(age_30_49_index,risk_immuno_index))) * (0.2428 - 0.2355)))] <- 1
  
  
  vax_assignment$vax_val[Reduce(intersect, list(age_50_64_index,risk_healthy_index,second_dose))] <- 1
  vax_assignment$vax_val[sample(setdiff(Reduce(intersect, list(age_50_64_index,risk_healthy_index)), second_dose), round(length(Reduce(intersect, list(age_50_64_index,risk_healthy_index))) * (0.1471 - 0.1439)))] <- 1
  vax_assignment$vax_val[Reduce(intersect, list(age_50_64_index,risk_highrisk_index,second_dose))] <- 1
  vax_assignment$vax_val[sample(setdiff(Reduce(intersect, list(age_50_64_index,risk_highrisk_index)), second_dose), round(length(Reduce(intersect, list(age_50_64_index,risk_highrisk_index))) * (0.2953 - 0.2591)))] <- 1
  vax_assignment$vax_val[Reduce(intersect, list(age_50_64_index,risk_immuno_index,second_dose))] <- 1
  vax_assignment$vax_val[sample(setdiff(Reduce(intersect, list(age_50_64_index,risk_immuno_index)), second_dose), round(length(Reduce(intersect, list(age_50_64_index,risk_immuno_index))) * (0.2953 - 0.2591)))] <- 1
  
  vax_assignment$vax_val[Reduce(intersect, list(age_65_74_index,risk_healthy_index,second_dose))] <- 1
  vax_assignment$vax_val[sample(setdiff(Reduce(intersect, list(age_65_74_index,risk_healthy_index)), second_dose), round(length(setdiff(Reduce(intersect, list(age_65_74_index,risk_healthy_index)), second_dose)) * (0.2334 - 0.2228)))] <- 1
  vax_assignment$vax_val[Reduce(intersect, list(age_65_74_index,risk_highrisk_index,second_dose))] <- 1
  vax_assignment$vax_val[sample(setdiff(Reduce(intersect, list(age_65_74_index,risk_highrisk_index)), second_dose), round(length(setdiff(Reduce(intersect, list(age_65_74_index,risk_highrisk_index)), second_dose)) * (0.4685 - 0.3710)))] <- 1
  vax_assignment$vax_val[Reduce(intersect, list(age_65_74_index,risk_immuno_index,second_dose))] <- 1
  vax_assignment$vax_val[sample(setdiff(Reduce(intersect, list(age_65_74_index,risk_immuno_index)), second_dose), round(length(setdiff(Reduce(intersect, list(age_65_74_index,risk_immuno_index)), second_dose)) * (0.4685 - 0.3710)))] <- 1
  
  vax_assignment$vax_val[Reduce(intersect, list(age_75_plus_index,risk_healthy_index,second_dose))] <- 1
  vax_assignment$vax_val[sample(setdiff(Reduce(intersect, list(age_75_plus_index,risk_healthy_index)), second_dose), round(length(setdiff(Reduce(intersect, list(age_75_plus_index,risk_healthy_index)), second_dose)) * (0.254 - 0.221)))] <- 1
  vax_assignment$vax_val[Reduce(intersect, list(age_75_plus_index,risk_highrisk_index,second_dose))] <- 1
  vax_assignment$vax_val[sample(setdiff(Reduce(intersect, list(age_75_plus_index,risk_highrisk_index)), second_dose), round(length(setdiff(Reduce(intersect, list(age_75_plus_index,risk_highrisk_index)), second_dose)) * (0.5097 - 0.3379)))] <- 1
  vax_assignment$vax_val[Reduce(intersect, list(age_75_plus_index,risk_immuno_index,second_dose))] <- 1
  vax_assignment$vax_val[sample(setdiff(Reduce(intersect, list(age_75_plus_index,risk_immuno_index)), second_dose), round(length(setdiff(Reduce(intersect, list(age_75_plus_index,risk_immuno_index)), second_dose)) * (0.5097 - 0.3379)))] <- 1
  
  print(paste0("Percentage of 0-17 years receiving vaccinated: ", length(which(vax_assignment$age_group == "0-17 years" & vax_assignment$vax_val == 1))/(length(which(vax_assignment$age_group == "0-17 years"))* 0.967)))
  print(paste0("Percentage of 18-29 years receiving vaccinated: ", length(which(vax_assignment$age_group == "18-29 years" & vax_assignment$vax_val == 1))/length(which(vax_assignment$age_group == "18-29 years"))))
  print(paste0("Percentage of 30-49 years receiving vaccinated: ", length(which(vax_assignment$age_group == "30-49 years" & vax_assignment$vax_val == 1))/length(which(vax_assignment$age_group == "30-49 years"))))
  print(paste0("Percentage of 50-64 years receiving vaccinated: ",  length(which(vax_assignment$age_group == "50-64 years" & vax_assignment$vax_val == 1))/length(which(vax_assignment$age_group == "50-64 years"))))
  print(paste0("Percentage of 65-74 years receiving vaccinated: ",  length(which(vax_assignment$age_group == "65-74 years" & vax_assignment$vax_val == 1))/length(which(vax_assignment$age_group == "65-74 years"))))
  print(paste0("Percentage of 75+ years receiving vaccinated: ",  length(which(vax_assignment$age_group == "75+ years" & vax_assignment$vax_val == 1))/length(which(vax_assignment$age_group == "75+ years"))))
  
  print(paste0("0-17 years, healthy: % vaccinated: ", length(which(vax_assignment$age_group == "0-17 years" & vax_assignment$risk_group == "healthy" & vax_assignment$vax_val == 1))/(length(which(vax_assignment$age_group == "0-17 years" & vax_assignment$risk_group == "healthy")) * 0.967)))
  print(paste0("18-29 years, healthy: % vaccinated: ", length(which(vax_assignment$age_group == "18-29 years" & vax_assignment$risk_group == "healthy" & vax_assignment$vax_val == 1))/length(which(vax_assignment$age_group == "18-29 years" & vax_assignment$risk_group == "healthy"))))
  print(paste0("30-49 years, healthy: % vaccinated: ", length(which(vax_assignment$age_group == "30-49 years" & vax_assignment$risk_group == "healthy" & vax_assignment$vax_val == 1))/length(which(vax_assignment$age_group == "30-49 years" & vax_assignment$risk_group == "healthy"))))
  print(paste0("50-64 years, healthy: % vaccinated: ",  length(which(vax_assignment$age_group == "50-64 years" & vax_assignment$risk_group == "healthy" & vax_assignment$vax_val == 1))/length(which(vax_assignment$age_group == "50-64 years" & vax_assignment$risk_group == "healthy"))))
  print(paste0("65-74 years, healthy: % vaccinated: ",  length(which(vax_assignment$age_group == "65-74 years" & vax_assignment$risk_group == "healthy" & vax_assignment$vax_val == 1))/length(which(vax_assignment$age_group == "65-74 years" & vax_assignment$risk_group == "healthy"))))
  print(paste0("75+ years, healthy: % vaccinated: ",  length(which(vax_assignment$age_group == "75+ years" & vax_assignment$risk_group == "healthy" & vax_assignment$vax_val == 1))/length(which(vax_assignment$age_group == "75+ years" & vax_assignment$risk_group == "healthy"))))
  print("0.1336, 0.0967, 0.1543, 0.2411, 0.4393, 0.478")
  
  print(paste0("0-17 years, higher risk: % vaccinated: ", length(which(vax_assignment$age_group == "0-17 years" & vax_assignment$risk_group == "higher risk" & vax_assignment$vax_val == 1))/(length(which(vax_assignment$age_group == "0-17 years" & vax_assignment$risk_group == "higher risk"))* 0.967)))
  print(paste0("18-29 years, higher risk: % vaccinated: ", length(which(vax_assignment$age_group == "18-29 years" & vax_assignment$risk_group == "higher risk" & vax_assignment$vax_val == 1))/length(which(vax_assignment$age_group == "18-29 years" & vax_assignment$risk_group == "higher risk"))))
  print(paste0("30-49 years, higher risk: % vaccinated: ", length(which(vax_assignment$age_group == "30-49 years" & vax_assignment$risk_group == "higher risk" & vax_assignment$vax_val == 1))/length(which(vax_assignment$age_group == "30-49 years" & vax_assignment$risk_group == "higher risk"))))
  print(paste0("50-64 years, higher risk: % vaccinated: ",  length(which(vax_assignment$age_group == "50-64 years" & vax_assignment$risk_group == "higher risk" & vax_assignment$vax_val == 1))/length(which(vax_assignment$age_group == "50-64 years" & vax_assignment$risk_group == "higher risk"))))
  print(paste0("65-74 years, higher risk: % vaccinated: ",  length(which(vax_assignment$age_group == "65-74 years" & vax_assignment$risk_group == "higher risk" & vax_assignment$vax_val == 1))/length(which(vax_assignment$age_group == "65-74 years" & vax_assignment$risk_group == "higher risk"))))
  print(paste0("75+ years, higher risk: % vaccinated: ",  length(which(vax_assignment$age_group == "75+ years" & vax_assignment$risk_group == "higher risk" & vax_assignment$vax_val == 1))/length(which(vax_assignment$age_group == "75+ years" & vax_assignment$risk_group == "higher risk"))))
  
  print(paste0("0-17 years, immunocompromised: % vaccinated: ", length(which(vax_assignment$age_group == "0-17 years" & vax_assignment$risk_group == "immunocompromised" & vax_assignment$vax_val == 1))/(length(which(vax_assignment$age_group == "0-17 years" & vax_assignment$risk_group == "immunocompromised"))* 0.967)))
  print(paste0("18-29 years, immunocompromised: % vaccinated: ", length(which(vax_assignment$age_group == "18-29 years" & vax_assignment$risk_group == "immunocompromised" & vax_assignment$vax_val == 1))/length(which(vax_assignment$age_group == "18-29 years" & vax_assignment$risk_group == "immunocompromised"))))
  print(paste0("30-49 years, immunocompromised: % vaccinated: ", length(which(vax_assignment$age_group == "30-49 years" & vax_assignment$risk_group == "immunocompromised" & vax_assignment$vax_val == 1))/length(which(vax_assignment$age_group == "30-49 years" & vax_assignment$risk_group == "immunocompromised"))))
  print(paste0("50-64 years, immunocompromised: % vaccinated: ",  length(which(vax_assignment$age_group == "50-64 years" & vax_assignment$risk_group == "immunocompromised" & vax_assignment$vax_val == 1))/length(which(vax_assignment$age_group == "50-64 years" & vax_assignment$risk_group == "immunocompromised"))))
  print(paste0("65-74 years, immunocompromised: % vaccinated: ",  length(which(vax_assignment$age_group == "65-74 years" & vax_assignment$risk_group == "immunocompromised" & vax_assignment$vax_val == 1))/length(which(vax_assignment$age_group == "65-74 years" & vax_assignment$risk_group == "immunocompromised"))))
  print(paste0("75+ years, immunocompromised: % vaccinated: ",  length(which(vax_assignment$age_group == "75+ years" & vax_assignment$risk_group == "immunocompromised" & vax_assignment$vax_val == 1))/length(which(vax_assignment$age_group == "75+ years" & vax_assignment$risk_group == "immunocompromised"))))
  
  
  #distribute booster uptake over next 365 days, according to age distributions
  to_vaccinate_index <- which(vax_assignment$vax == 1)
  
  vax_assignment$vaccine_wave[Reduce(intersect, list(age_0_17_index,risk_healthy_index,to_vaccinate_index))] <- sample(c(1:365), length(Reduce(intersect, list(age_0_17_index,risk_healthy_index,to_vaccinate_index))), prob = c(((vaccine_coverage_by_age %>% filter(age_group == "0-17 years", risk_group == "healthy") %>% arrange(week))$prop_up_to_date_sim_period)[1], rep((vaccine_coverage_by_age %>% filter(age_group == "0-17 years", risk_group == "healthy") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$vaccine_wave[Reduce(intersect, list(age_0_17_index,risk_highrisk_index,to_vaccinate_index))] <- sample(c(1:365), length(Reduce(intersect, list(age_0_17_index,risk_highrisk_index,to_vaccinate_index))), prob = c(((vaccine_coverage_by_age %>% filter(age_group == "0-17 years", risk_group == "higher risk") %>% arrange(week))$prop_up_to_date_sim_period)[1], rep((vaccine_coverage_by_age %>% filter(age_group == "0-17 years", risk_group == "higher risk") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$vaccine_wave[Reduce(intersect, list(age_0_17_index,risk_immuno_index,to_vaccinate_index))] <- sample(c(1:365), length(Reduce(intersect, list(age_0_17_index,risk_immuno_index,to_vaccinate_index))), prob = c(((vaccine_coverage_by_age %>% filter(age_group == "0-17 years", risk_group == "immunocompromised") %>% arrange(week))$prop_up_to_date_sim_period)[1], rep((vaccine_coverage_by_age %>% filter(age_group == "0-17 years", risk_group == "immunocompromised") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  
  vax_assignment$vaccine_wave[Reduce(intersect, list(age_18_29_index,risk_healthy_index,to_vaccinate_index))] <- sample(c(1:365), length(Reduce(intersect, list(age_18_29_index,risk_healthy_index,to_vaccinate_index))), prob = c(((vaccine_coverage_by_age %>% filter(age_group == "18-29 years", risk_group == "healthy") %>% arrange(week))$prop_up_to_date_sim_period)[1], rep((vaccine_coverage_by_age %>% filter(age_group == "18-29 years", risk_group == "healthy") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$vaccine_wave[Reduce(intersect, list(age_18_29_index,risk_highrisk_index,to_vaccinate_index))] <- sample(c(1:365), length(Reduce(intersect, list(age_18_29_index,risk_highrisk_index,to_vaccinate_index))), prob = c(((vaccine_coverage_by_age %>% filter(age_group == "18-29 years", risk_group == "higher risk") %>% arrange(week))$prop_up_to_date_sim_period)[1], rep((vaccine_coverage_by_age %>% filter(age_group == "18-29 years", risk_group == "higher risk") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$vaccine_wave[Reduce(intersect, list(age_18_29_index,risk_immuno_index,to_vaccinate_index))] <- sample(c(1:365), length(Reduce(intersect, list(age_18_29_index,risk_immuno_index,to_vaccinate_index))), prob = c(((vaccine_coverage_by_age %>% filter(age_group == "18-29 years", risk_group == "immunocompromised") %>% arrange(week))$prop_up_to_date_sim_period)[1], rep((vaccine_coverage_by_age %>% filter(age_group == "18-29 years", risk_group == "immunocompromised") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  
  vax_assignment$vaccine_wave[Reduce(intersect, list(age_30_49_index,risk_healthy_index,to_vaccinate_index))] <- sample(c(1:365), length(Reduce(intersect, list(age_30_49_index,risk_healthy_index,to_vaccinate_index))), prob = c(((vaccine_coverage_by_age %>% filter(age_group == "30-49 years", risk_group == "healthy") %>% arrange(week))$prop_up_to_date_sim_period)[1], rep((vaccine_coverage_by_age %>% filter(age_group == "30-49 years", risk_group == "healthy") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$vaccine_wave[Reduce(intersect, list(age_30_49_index,risk_highrisk_index,to_vaccinate_index))] <- sample(c(1:365), length(Reduce(intersect, list(age_30_49_index,risk_highrisk_index,to_vaccinate_index))), prob = c(((vaccine_coverage_by_age %>% filter(age_group == "30-49 years", risk_group == "higher risk") %>% arrange(week))$prop_up_to_date_sim_period)[1], rep((vaccine_coverage_by_age %>% filter(age_group == "30-49 years", risk_group == "higher risk") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$vaccine_wave[Reduce(intersect, list(age_30_49_index,risk_immuno_index,to_vaccinate_index))] <- sample(c(1:365), length(Reduce(intersect, list(age_30_49_index,risk_immuno_index,to_vaccinate_index))), prob = c(((vaccine_coverage_by_age %>% filter(age_group == "30-49 years", risk_group == "immunocompromised") %>% arrange(week))$prop_up_to_date_sim_period)[1], rep((vaccine_coverage_by_age %>% filter(age_group == "30-49 years", risk_group == "immunocompromised") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  
  vax_assignment$vaccine_wave[Reduce(intersect, list(age_50_64_index,risk_healthy_index,to_vaccinate_index))] <- sample(c(1:365), length(Reduce(intersect, list(age_50_64_index,risk_healthy_index,to_vaccinate_index))), prob = c(((vaccine_coverage_by_age %>% filter(age_group == "50-64 years", risk_group == "healthy") %>% arrange(week))$prop_up_to_date_sim_period)[1], rep((vaccine_coverage_by_age %>% filter(age_group == "50-64 years", risk_group == "healthy") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$vaccine_wave[Reduce(intersect, list(age_50_64_index,risk_highrisk_index,to_vaccinate_index))] <- sample(c(1:365), length(Reduce(intersect, list(age_50_64_index,risk_highrisk_index,to_vaccinate_index))), prob = c(((vaccine_coverage_by_age %>% filter(age_group == "50-64 years", risk_group == "higher risk") %>% arrange(week))$prop_up_to_date_sim_period)[1], rep((vaccine_coverage_by_age %>% filter(age_group == "50-64 years", risk_group == "higher risk") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$vaccine_wave[Reduce(intersect, list(age_50_64_index,risk_immuno_index,to_vaccinate_index))] <- sample(c(1:365), length(Reduce(intersect, list(age_50_64_index,risk_immuno_index,to_vaccinate_index))), prob = c(((vaccine_coverage_by_age %>% filter(age_group == "50-64 years", risk_group == "immunocompromised") %>% arrange(week))$prop_up_to_date_sim_period)[1], rep((vaccine_coverage_by_age %>% filter(age_group == "50-64 years", risk_group == "immunocompromised") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  
  vax_assignment$vaccine_wave[Reduce(intersect, list(age_65_74_index,risk_healthy_index,to_vaccinate_index))] <- sample(c(1:365), length(Reduce(intersect, list(age_65_74_index,risk_healthy_index,to_vaccinate_index))), prob = c(((vaccine_coverage_by_age %>% filter(age_group == "65-74 years", risk_group == "healthy") %>% arrange(week))$prop_up_to_date_sim_period)[1], rep((vaccine_coverage_by_age %>% filter(age_group == "65-74 years", risk_group == "healthy") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$vaccine_wave[Reduce(intersect, list(age_65_74_index,risk_highrisk_index,to_vaccinate_index))] <- sample(c(1:365), length(Reduce(intersect, list(age_65_74_index,risk_highrisk_index,to_vaccinate_index))), prob = c(((vaccine_coverage_by_age %>% filter(age_group == "65-74 years", risk_group == "higher risk") %>% arrange(week))$prop_up_to_date_sim_period)[1], rep((vaccine_coverage_by_age %>% filter(age_group == "65-74 years", risk_group == "higher risk") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$vaccine_wave[Reduce(intersect, list(age_65_74_index,risk_immuno_index,to_vaccinate_index))] <- sample(c(1:365), length(Reduce(intersect, list(age_65_74_index,risk_immuno_index,to_vaccinate_index))), prob = c(((vaccine_coverage_by_age %>% filter(age_group == "65-74 years", risk_group == "immunocompromised") %>% arrange(week))$prop_up_to_date_sim_period)[1], rep((vaccine_coverage_by_age %>% filter(age_group == "65-74 years", risk_group == "immunocompromised") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  
  vax_assignment$vaccine_wave[Reduce(intersect, list(age_75_plus_index,risk_healthy_index,to_vaccinate_index))] <- sample(c(1:365), length(Reduce(intersect, list(age_75_plus_index,risk_healthy_index,to_vaccinate_index))), prob = c(((vaccine_coverage_by_age %>% filter(age_group == "75+ years", risk_group == "healthy") %>% arrange(week))$prop_up_to_date_sim_period)[1], rep((vaccine_coverage_by_age %>% filter(age_group == "75+ years", risk_group == "healthy") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$vaccine_wave[Reduce(intersect, list(age_75_plus_index,risk_highrisk_index,to_vaccinate_index))] <- sample(c(1:365), length(Reduce(intersect, list(age_75_plus_index,risk_highrisk_index,to_vaccinate_index))), prob = c(((vaccine_coverage_by_age %>% filter(age_group == "75+ years", risk_group == "higher risk") %>% arrange(week))$prop_up_to_date_sim_period)[1], rep((vaccine_coverage_by_age %>% filter(age_group == "75+ years", risk_group == "higher risk") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$vaccine_wave[Reduce(intersect, list(age_75_plus_index,risk_immuno_index,to_vaccinate_index))] <- sample(c(1:365), length(Reduce(intersect, list(age_75_plus_index,risk_immuno_index,to_vaccinate_index))), prob = c(((vaccine_coverage_by_age %>% filter(age_group == "75+ years", risk_group == "immunocompromised") %>% arrange(week))$prop_up_to_date_sim_period)[1], rep((vaccine_coverage_by_age %>% filter(age_group == "75+ years", risk_group == "immunocompromised") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  
  #distribute second dose booster uptake over next 365 days, according to age distributions
  to_vaccinate_second_index <- which(vax_assignment$vax_2 == 1)
  
  vax_assignment$second_vaccine_wave[Reduce(intersect, list(age_18_29_index,risk_immuno_index,to_vaccinate_second_index))] <- sample(c(240:365), length(Reduce(intersect, list(age_18_29_index,risk_immuno_index,to_vaccinate_second_index))), prob = c(rep((second_dose_annually_vaccine_coverage %>% filter(age_group == "18-29 years", risk_group == "immunocompromised") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  
  vax_assignment$second_vaccine_wave[Reduce(intersect, list(age_30_49_index,risk_immuno_index,to_vaccinate_second_index))] <- sample(c(240:365), length(Reduce(intersect, list(age_30_49_index,risk_immuno_index,to_vaccinate_second_index))), prob = c(rep((second_dose_annually_vaccine_coverage %>% filter(age_group == "30-49 years", risk_group == "immunocompromised") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  
  vax_assignment$second_vaccine_wave[Reduce(intersect, list(age_50_64_index,risk_immuno_index,to_vaccinate_second_index))] <- sample(c(240:365), length(Reduce(intersect, list(age_50_64_index,risk_immuno_index,to_vaccinate_second_index))), prob = c(rep((second_dose_annually_vaccine_coverage %>% filter(age_group == "50-64 years", risk_group == "immunocompromised") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  
  vax_assignment$second_vaccine_wave[Reduce(intersect, list(age_65_74_index,risk_healthy_index,to_vaccinate_second_index))] <- sample(c(240:365), length(Reduce(intersect, list(age_65_74_index,risk_healthy_index,to_vaccinate_second_index))), prob = c(rep((second_dose_annually_vaccine_coverage %>% filter(age_group == "65-74 years", risk_group == "healthy") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$second_vaccine_wave[Reduce(intersect, list(age_65_74_index,risk_highrisk_index,to_vaccinate_second_index))] <- sample(c(240:365), length(Reduce(intersect, list(age_65_74_index,risk_highrisk_index,to_vaccinate_second_index))), prob = c(rep((second_dose_annually_vaccine_coverage %>% filter(age_group == "65-74 years", risk_group == "higher risk") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$second_vaccine_wave[Reduce(intersect, list(age_65_74_index,risk_immuno_index,to_vaccinate_second_index))] <- sample(c(240:365), length(Reduce(intersect, list(age_65_74_index,risk_immuno_index,to_vaccinate_second_index))), prob = c(rep((second_dose_annually_vaccine_coverage %>% filter(age_group == "65-74 years", risk_group == "immunocompromised") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  
  vax_assignment$second_vaccine_wave[Reduce(intersect, list(age_75_plus_index,risk_healthy_index,to_vaccinate_second_index))] <- sample(c(240:365), length(Reduce(intersect, list(age_75_plus_index,risk_healthy_index,to_vaccinate_second_index))), prob = c(rep((second_dose_annually_vaccine_coverage %>% filter(age_group == "75+ years", risk_group == "healthy") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$second_vaccine_wave[Reduce(intersect, list(age_75_plus_index,risk_highrisk_index,to_vaccinate_second_index))] <- sample(c(240:365), length(Reduce(intersect, list(age_75_plus_index,risk_highrisk_index,to_vaccinate_second_index))), prob = c(rep((second_dose_annually_vaccine_coverage %>% filter(age_group == "75+ years", risk_group == "higher risk") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$second_vaccine_wave[Reduce(intersect, list(age_75_plus_index,risk_immuno_index,to_vaccinate_second_index))] <- sample(c(240:365), length(Reduce(intersect, list(age_75_plus_index,risk_immuno_index,to_vaccinate_second_index))), prob = c(rep((second_dose_annually_vaccine_coverage %>% filter(age_group == "75+ years", risk_group == "immunocompromised") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  
  
  #distribute booster uptake over next 182 days, according to age distributions
  to_vaccinate_index <- which(vax_assignment$vax_val == 1)
  
  vax_assignment$vaccine_wave_val[Reduce(intersect, list(age_0_17_index,risk_healthy_index,to_vaccinate_index))] <- sample(c((1 + 365):(182 + 365)), length(Reduce(intersect, list(age_0_17_index,risk_healthy_index,to_vaccinate_index))), prob = c(rep((vaccine_coverage_by_age_validation %>% filter(age_group == "0-17 years", risk_group == "healthy") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$vaccine_wave_val[Reduce(intersect, list(age_0_17_index,risk_highrisk_index,to_vaccinate_index))] <- sample(c((1 + 365):(182 + 365)), length(Reduce(intersect, list(age_0_17_index,risk_highrisk_index,to_vaccinate_index))), prob = c(rep((vaccine_coverage_by_age_validation %>% filter(age_group == "0-17 years", risk_group == "higher risk") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$vaccine_wave_val[Reduce(intersect, list(age_0_17_index,risk_immuno_index,to_vaccinate_index))] <- sample(c((1 + 365):(182 + 365)), length(Reduce(intersect, list(age_0_17_index,risk_immuno_index,to_vaccinate_index))), prob = c(rep((vaccine_coverage_by_age_validation %>% filter(age_group == "0-17 years", risk_group == "immunocompromised") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  
  vax_assignment$vaccine_wave_val[Reduce(intersect, list(age_18_29_index,risk_healthy_index,to_vaccinate_index))] <- sample(c((1 + 365):(182 + 365)), length(Reduce(intersect, list(age_18_29_index,risk_healthy_index,to_vaccinate_index))), prob = c(rep((vaccine_coverage_by_age_validation %>% filter(age_group == "18-29 years", risk_group == "healthy") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$vaccine_wave_val[Reduce(intersect, list(age_18_29_index,risk_highrisk_index,to_vaccinate_index))] <- sample(c((1 + 365):(182 + 365)), length(Reduce(intersect, list(age_18_29_index,risk_highrisk_index,to_vaccinate_index))), prob = c(rep((vaccine_coverage_by_age_validation %>% filter(age_group == "18-29 years", risk_group == "higher risk") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$vaccine_wave_val[Reduce(intersect, list(age_18_29_index,risk_immuno_index,to_vaccinate_index))] <- sample(c((1 + 365):(182 + 365)), length(Reduce(intersect, list(age_18_29_index,risk_immuno_index,to_vaccinate_index))), prob = c(rep((vaccine_coverage_by_age_validation %>% filter(age_group == "18-29 years", risk_group == "immunocompromised") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  
  vax_assignment$vaccine_wave_val[Reduce(intersect, list(age_30_49_index,risk_healthy_index,to_vaccinate_index))] <- sample(c((1 + 365):(182 + 365)), length(Reduce(intersect, list(age_30_49_index,risk_healthy_index,to_vaccinate_index))), prob = c(rep((vaccine_coverage_by_age_validation %>% filter(age_group == "30-49 years", risk_group == "healthy") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$vaccine_wave_val[Reduce(intersect, list(age_30_49_index,risk_highrisk_index,to_vaccinate_index))] <- sample(c((1 + 365):(182 + 365)), length(Reduce(intersect, list(age_30_49_index,risk_highrisk_index,to_vaccinate_index))), prob = c(rep((vaccine_coverage_by_age_validation %>% filter(age_group == "30-49 years", risk_group == "higher risk") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$vaccine_wave_val[Reduce(intersect, list(age_30_49_index,risk_immuno_index,to_vaccinate_index))] <- sample(c((1 + 365):(182 + 365)), length(Reduce(intersect, list(age_30_49_index,risk_immuno_index,to_vaccinate_index))), prob = c(rep((vaccine_coverage_by_age_validation %>% filter(age_group == "30-49 years", risk_group == "immunocompromised") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  
  vax_assignment$vaccine_wave_val[Reduce(intersect, list(age_50_64_index,risk_healthy_index,to_vaccinate_index))] <- sample(c((1 + 365):(182 + 365)), length(Reduce(intersect, list(age_50_64_index,risk_healthy_index,to_vaccinate_index))), prob = c(rep((vaccine_coverage_by_age_validation %>% filter(age_group == "50-64 years", risk_group == "healthy") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$vaccine_wave_val[Reduce(intersect, list(age_50_64_index,risk_highrisk_index,to_vaccinate_index))] <- sample(c((1 + 365):(182 + 365)), length(Reduce(intersect, list(age_50_64_index,risk_highrisk_index,to_vaccinate_index))), prob = c(rep((vaccine_coverage_by_age_validation %>% filter(age_group == "50-64 years", risk_group == "higher risk") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$vaccine_wave_val[Reduce(intersect, list(age_50_64_index,risk_immuno_index,to_vaccinate_index))] <- sample(c((1 + 365):(182 + 365)), length(Reduce(intersect, list(age_50_64_index,risk_immuno_index,to_vaccinate_index))), prob = c(rep((vaccine_coverage_by_age_validation %>% filter(age_group == "50-64 years", risk_group == "immunocompromised") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  
  vax_assignment$vaccine_wave_val[Reduce(intersect, list(age_65_74_index,risk_healthy_index,to_vaccinate_index))] <- sample(c((1 + 365):(182 + 365)), length(Reduce(intersect, list(age_65_74_index,risk_healthy_index,to_vaccinate_index))), prob = c(rep((vaccine_coverage_by_age_validation %>% filter(age_group == "65-74 years", risk_group == "healthy") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$vaccine_wave_val[Reduce(intersect, list(age_65_74_index,risk_highrisk_index,to_vaccinate_index))] <- sample(c((1 + 365):(182 + 365)), length(Reduce(intersect, list(age_65_74_index,risk_highrisk_index,to_vaccinate_index))), prob = c(rep((vaccine_coverage_by_age_validation %>% filter(age_group == "65-74 years", risk_group == "higher risk") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$vaccine_wave_val[Reduce(intersect, list(age_65_74_index,risk_immuno_index,to_vaccinate_index))] <- sample(c((1 + 365):(182 + 365)), length(Reduce(intersect, list(age_65_74_index,risk_immuno_index,to_vaccinate_index))), prob = c(rep((vaccine_coverage_by_age_validation %>% filter(age_group == "65-74 years", risk_group == "immunocompromised") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  
  vax_assignment$vaccine_wave_val[Reduce(intersect, list(age_75_plus_index,risk_healthy_index,to_vaccinate_index))] <- sample(c((1 + 365):(182 + 365)), length(Reduce(intersect, list(age_75_plus_index,risk_healthy_index,to_vaccinate_index))), prob = c(rep((vaccine_coverage_by_age_validation %>% filter(age_group == "75+ years", risk_group == "healthy") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$vaccine_wave_val[Reduce(intersect, list(age_75_plus_index,risk_highrisk_index,to_vaccinate_index))] <- sample(c((1 + 365):(182 + 365)), length(Reduce(intersect, list(age_75_plus_index,risk_highrisk_index,to_vaccinate_index))), prob = c(rep((vaccine_coverage_by_age_validation %>% filter(age_group == "75+ years", risk_group == "higher risk") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  vax_assignment$vaccine_wave_val[Reduce(intersect, list(age_75_plus_index,risk_immuno_index,to_vaccinate_index))] <- sample(c((1 + 365):(182 + 365)), length(Reduce(intersect, list(age_75_plus_index,risk_immuno_index,to_vaccinate_index))), prob = c(rep((vaccine_coverage_by_age_validation %>% filter(age_group == "75+ years", risk_group == "immunocompromised") %>% arrange(week))$prop_up_to_date_sim_period, each = 7)), replace = TRUE)
  
  return(vax_assignment %>% arrange(individual))
}